# Generated by Django 2.1.7 on 2019-03-18 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Address'),
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='books.Invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.TaxRate'),
        ),
        migrations.AddField(
            model_name='invoicecontribution',
            name='contribution_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.ContributionRate'),
        ),
        migrations.AddField(
            model_name='invoicecontribution',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='books.Invoice'),
        ),
        migrations.AddField(
            model_name='invoicecontribution',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.TaxRate'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Client', verbose_name='To Client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='books.Organization', verbose_name='From Organization'),
        ),
        migrations.AddField(
            model_name='expenseclaimline',
            name='expense_claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='books.ExpenseClaim'),
        ),
        migrations.AddField(
            model_name='expenseclaimline',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.TaxRate'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Employee', verbose_name='Paid by employee'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to='books.Organization', verbose_name='From Organization'),
        ),
        migrations.AddField(
            model_name='estimateline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='books.Estimate'),
        ),
        migrations.AddField(
            model_name='estimateline',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.TaxRate'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Client', verbose_name='To Client'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='books.Organization', verbose_name='From Organization'),
        ),
        migrations.AddField(
            model_name='contributionrate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withholding_rates', to='books.Organization', verbose_name='Attached to Organization'),
        ),
        migrations.AddField(
            model_name='billline',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='books.Bill'),
        ),
        migrations.AddField(
            model_name='billline',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.TaxRate'),
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Client', verbose_name='From Client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='books.Organization', verbose_name='To Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='expenseclaim',
            unique_together={('number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('number', 'organization')},
        ),
    ]
