# Generated by Django 2.1.7 on 2019-03-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190318_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='vat_number',
            field=models.CharField(help_text='Fiscal id of the organization', max_length=30, null=True),
        ),
    ]
