# Generated by Django 2.1.4 on 2019-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190309_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_dued',
            field=models.DateField(blank=True, default=None, help_text='The date when the total amount should have been collected', null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='date_dued',
            field=models.DateField(blank=True, default=None, help_text='The date when the total amount should have been collected', null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='date_dued',
            field=models.DateField(blank=True, default=None, help_text='The date when the total amount should have been collected', null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_dued',
            field=models.DateField(blank=True, default=None, help_text='The date when the total amount should have been collected', null=True, verbose_name='Due date'),
        ),
    ]
