# Generated by Django 2.1.7 on 2019-03-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_organization_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='vat_number',
            field=models.CharField(help_text='Fiscal id of the organization', max_length=30, unique=True),
        ),
    ]
