# Generated by Django 2.1.4 on 2019-03-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190309_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='display_name',
            new_name='name',
        ),
    ]
