# Generated by Django 2.1.4 on 2019-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190311_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Business communicated name', max_length=150),
        ),
    ]
