# Generated by Django 2.1.4 on 2019-03-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='%(class)s smart name', max_length=150),
        ),
    ]
