# Generated by Django 2.1.7 on 2019-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vat_number',
            field=models.CharField(help_text='Fiscal id of the client', max_length=30, null=True),
        ),
    ]
